name: Build and Deploy Docker to Azure

on:
  push:
    branches:
      - definitive  # o tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/miapp:latest .
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/miapp:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: mi-webapp-docker
          images: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/miapp:latest
